// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "krak8s": goa_namespace Resource Client
//
// Command:
// $ goagen
// --design=krak8s/design
// --out=$(GOPATH)/src/krak8s
// --version=v1.2.0-dirty

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateGoaNamespacePayload is the goa_namespace create action payload.
type CreateGoaNamespacePayload struct {
	Name string `form:"name" json:"name" xml:"name"`
}

// CreateGoaNamespacePath computes a request path to the create action of goa_namespace.
func CreateGoaNamespacePath(project string) string {
	param0 := project

	return fmt.Sprintf("/v1/projects/%s/ns", param0)
}

// Create a namespace in the specified project
func (c *Client) CreateGoaNamespace(ctx context.Context, path string, payload *CreateGoaNamespacePayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateGoaNamespaceRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateGoaNamespaceRequest create the request corresponding to the create action endpoint of the goa_namespace resource.
func (c *Client) NewCreateGoaNamespaceRequest(ctx context.Context, path string, payload *CreateGoaNamespacePayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// DeleteGoaNamespacePath computes a request path to the delete action of goa_namespace.
func DeleteGoaNamespacePath(project string, ns string) string {
	param0 := project
	param1 := ns

	return fmt.Sprintf("/v1/projects/%s/ns/%s", param0, param1)
}

// Delete the specified namespace (ns)
func (c *Client) DeleteGoaNamespace(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteGoaNamespaceRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteGoaNamespaceRequest create the request corresponding to the delete action endpoint of the goa_namespace resource.
func (c *Client) NewDeleteGoaNamespaceRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// GetGoaNamespacePath computes a request path to the get action of goa_namespace.
func GetGoaNamespacePath(project string, ns string) string {
	param0 := project
	param1 := ns

	return fmt.Sprintf("/v1/projects/%s/ns/%s", param0, param1)
}

// Get the details of the specified namespace (ns) in the project
func (c *Client) GetGoaNamespace(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetGoaNamespaceRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetGoaNamespaceRequest create the request corresponding to the get action endpoint of the goa_namespace resource.
func (c *Client) NewGetGoaNamespaceRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ListGoaNamespacePath computes a request path to the list action of goa_namespace.
func ListGoaNamespacePath(project string) string {
	param0 := project

	return fmt.Sprintf("/v1/projects/%s/ns", param0)
}

// Retrieve the collection of all namespaces in the project.
func (c *Client) ListGoaNamespace(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListGoaNamespaceRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListGoaNamespaceRequest create the request corresponding to the list action endpoint of the goa_namespace resource.
func (c *Client) NewListGoaNamespaceRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
