// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "krak8s": goa_project Resource Client
//
// Command:
// $ goagen
// --design=krak8s/design
// --out=$(GOPATH)/src/krak8s
// --version=v1.2.0-dirty

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateGoaProjectPayload is the goa_project create action payload.
type CreateGoaProjectPayload struct {
	Identity string `form:"identity" json:"identity" xml:"identity"`
}

// CreateGoaProjectPath computes a request path to the create action of goa_project.
func CreateGoaProjectPath() string {

	return fmt.Sprintf("/v1/projects")
}

// Create a new user/project
func (c *Client) CreateGoaProject(ctx context.Context, path string, payload *CreateGoaProjectPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateGoaProjectRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateGoaProjectRequest create the request corresponding to the create action endpoint of the goa_project resource.
func (c *Client) NewCreateGoaProjectRequest(ctx context.Context, path string, payload *CreateGoaProjectPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// DeleteGoaProjectPath computes a request path to the delete action of goa_project.
func DeleteGoaProjectPath(project string) string {
	param0 := project

	return fmt.Sprintf("/v1/projects/%s", param0)
}

// DeleteGoaProject makes a request to the delete action endpoint of the goa_project resource
func (c *Client) DeleteGoaProject(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteGoaProjectRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteGoaProjectRequest create the request corresponding to the delete action endpoint of the goa_project resource.
func (c *Client) NewDeleteGoaProjectRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// GetGoaProjectPath computes a request path to the get action of goa_project.
func GetGoaProjectPath(project string) string {
	param0 := project

	return fmt.Sprintf("/v1/projects/%s", param0)
}

// Retrieve project with given id.
func (c *Client) GetGoaProject(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetGoaProjectRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetGoaProjectRequest create the request corresponding to the get action endpoint of the goa_project resource.
func (c *Client) NewGetGoaProjectRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ListGoaProjectPath computes a request path to the list action of goa_project.
func ListGoaProjectPath() string {

	return fmt.Sprintf("/v1/projects")
}

// Retrieve all projects.
func (c *Client) ListGoaProject(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListGoaProjectRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListGoaProjectRequest create the request corresponding to the list action endpoint of the goa_project resource.
func (c *Client) NewListGoaProjectRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
