// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "krak8s": namespace Resource Client
//
// Command:
// $ goagen
// --design=krak8s/design
// --out=$(GOPATH)/src/krak8s
// --version=v1.2.0-dirty

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateNamespacePayload is the namespace create action payload.
type CreateNamespacePayload struct {
	Name string `form:"name" json:"name" xml:"name"`
}

// CreateNamespacePath computes a request path to the create action of namespace.
func CreateNamespacePath(projectid string) string {
	param0 := projectid

	return fmt.Sprintf("/v1/projects/%s/namespaces", param0)
}

// Create a namespace in the specified project
func (c *Client) CreateNamespace(ctx context.Context, path string, payload *CreateNamespacePayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateNamespaceRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateNamespaceRequest create the request corresponding to the create action endpoint of the namespace resource.
func (c *Client) NewCreateNamespaceRequest(ctx context.Context, path string, payload *CreateNamespacePayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// DeleteNamespacePath computes a request path to the delete action of namespace.
func DeleteNamespacePath(projectid string, namespaceid string) string {
	param0 := projectid
	param1 := namespaceid

	return fmt.Sprintf("/v1/projects/%s/namespaces/%s", param0, param1)
}

// Delete the specified namespace from the project
func (c *Client) DeleteNamespace(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteNamespaceRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteNamespaceRequest create the request corresponding to the delete action endpoint of the namespace resource.
func (c *Client) NewDeleteNamespaceRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// GetNamespacePath computes a request path to the get action of namespace.
func GetNamespacePath(projectid string, namespaceid string) string {
	param0 := projectid
	param1 := namespaceid

	return fmt.Sprintf("/v1/projects/%s/namespaces/%s", param0, param1)
}

// Get the details of the specified namespace in the project
func (c *Client) GetNamespace(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetNamespaceRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetNamespaceRequest create the request corresponding to the get action endpoint of the namespace resource.
func (c *Client) NewGetNamespaceRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
