// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "krak8s": Application Controllers
//
// Command:
// $ goagen
// --design=krak8s/design
// --out=$(GOPATH)/src/krak8s
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// MongodbController is the controller interface for the Mongodb actions.
type MongodbController interface {
	goa.Muxer
	Deploy(*DeployMongodbContext) error
}

// MountMongodbController "mounts" a Mongodb resource controller on the given service.
func MountMongodbController(service *goa.Service, ctrl MongodbController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewDeployMongodbContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Deploy(rctx)
	}
	service.Mux.Handle("POST", "/v1/mongo/", ctrl.MuxHandler("deploy", h, nil))
	service.LogInfo("mount", "ctrl", "Mongodb", "action", "Deploy", "route", "POST /v1/mongo/")
}
