// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "krak8s": Application Contexts
//
// Command:
// $ goagen
// --design=krak8s/design
// --out=$(GOPATH)/src/krak8s
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// DeployMongodbContext provides the mongodb deploy action context.
type DeployMongodbContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Client *string
	Ns     *string
}

// NewDeployMongodbContext parses the incoming request URL and body, performs validations and creates the
// context used by the mongodb controller deploy action.
func NewDeployMongodbContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeployMongodbContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeployMongodbContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramClient := req.Params["client"]
	if len(paramClient) > 0 {
		rawClient := paramClient[0]
		rctx.Client = &rawClient
	}
	paramNs := req.Params["ns"]
	if len(paramNs) > 0 {
		rawNs := paramNs[0]
		rctx.Ns = &rawNs
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DeployMongodbContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}
