// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "krak8s": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=krak8s/design
// --out=$(GOPATH)/src/krak8s
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// GoaMongoHref returns the resource href.
func GoaMongoHref(project, ns interface{}) string {
	paramproject := strings.TrimLeftFunc(fmt.Sprintf("%v", project), func(r rune) bool { return r == '/' })
	paramns := strings.TrimLeftFunc(fmt.Sprintf("%v", ns), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/projects/%v/ns/%v/mongo", paramproject, paramns)
}

// GoaNamespaceHref returns the resource href.
func GoaNamespaceHref(project, ns interface{}) string {
	paramproject := strings.TrimLeftFunc(fmt.Sprintf("%v", project), func(r rune) bool { return r == '/' })
	paramns := strings.TrimLeftFunc(fmt.Sprintf("%v", ns), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/projects/%v/ns/%v", paramproject, paramns)
}

// GoaProjectHref returns the resource href.
func GoaProjectHref(project interface{}) string {
	paramproject := strings.TrimLeftFunc(fmt.Sprintf("%v", project), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/projects/%v", paramproject)
}
